---
# Variables:
#  _service_own_path  the path to give the system account ownership to.

- name: ensure service account owns {{ _service_own_path }}
  when: _irods_cfg_chown
  file:
    dest: "{{ _service_own_path }}"
    owner: "{{ _irods_cfg_system_account_name }}"
    group: "{{ _irods_cfg_system_group_name }}"
