---
- when: _irods_cfg_icat is mapping
  block:
    - name: validate database config params
      assert:
        that:
          - _irods_cfg_icat.catalog_database_type in ('mysql', 'oracle', 'postgres')
          - _irods_cfg_icat.db_port | int >= 1 and _irods_cfg_icat.db_port | int <= 65535

    - name: generate database_config.json
      template:
        src: database_config.json.j2
        dest: /etc/irods/database_config.json
        owner: "{{ _irods_cfg_service_account_name }}"
        group: "{{ _irods_cfg_service_group_name }}"
      notify:
        - changed config

- meta: flush_handlers
