---
- name: validate hosts config vars
  fail:
    msg: not implemented
  failed_when: false

- name: generate hosts_config.json
  template:
    src: hosts_config.json.j2
    dest: /etc/irods/hosts_config.json
    owner: "{{ _irods_server_cfg_service_account_name }}"
    group: "{{ _irods_server_cfg_service_group_name }}"
