---
- name: validate address type for hosts_config
  when: _irods_cfg_validate
  with_items: "{{ _irods_cfg_host_entries }}"
  assert:
    that:
      - item.address_type == 'local' or item.address_type == 'remote'
  ignore_errors: true

- include_tasks: _cfg_template.yml
  vars:
    _cfg_template_dest_file: etc/irods/hosts_config.json

- meta: flush_handlers
