---
- name: initialize clerver connection
  shell: |
    bak='{{ irods_cfg_authentication_file }}.bak'
    trap "rm --force '$bak'" EXIT

    if [[ -f '{{ irods_cfg_authentication_file }}' ]]
    then
      cp '{{ irods_cfg_authentication_file }}' "$bak"
    else
      touch "$bak"
    fi

    if ! iinit '{{ _irods_cfg_zone_password }}'
    then
      exit 1
    fi

    if ! diff --brief "$bak" '{{ irods_cfg_authentication_file }}' 2> /dev/null
    then
      printf 'changed'
    fi
  register: __result
  changed_when: __result.stdout == 'changed'
