---
- name: validate variables
  assert:
    that:
      - 'not _irods_server_cfg_client_server_negotiation
         or _irods_server_cfg_client_server_negotiation in ["none", "request_server_negotiation"]'
      - 'not _irods_server_cfg_client_server_policy
         or _irods_server_cfg_client_server_policy
              in ["CS_NEG_DONT_CARE", "CS_NEG_REFUSE", "CS_NEG_REQUIRE"]'
      - not _irods_server_cfg_debug or _irods_server_cfg_debug | int >= 0
      - 'not _irods_server_cfg_server_control_plane_key
         or _irods_server_cfg_server_control_plane_key | length == 32'
      - 'not _irods_server_cfg_server_control_plane_port
         or (_irods_server_cfg_server_control_plane_port | int >= 1
             and _irods_server_cfg_server_control_plane_port | int <= 65535)'
      - not _irods_server_cfg_cwd or _irods_server_cfg_cwd | match('^/..*')
      - 'not _irods_server_cfg_clerver_default_hash_scheme
         or _irods_server_cfg_clerver_default_hash_scheme in ["MD5", "SHA256"]'
      - 'not _irods_server_cfg_clerver_encryption_key_size
         or _irods_server_cfg_clerver_encryption_key_size | int >= 0'
      - 'not _irods_server_cfg_clerver_encryption_num_hash_rounds
         or _irods_server_cfg_clerver_encryption_num_hash_rounds | int >= 0'
      - 'not _irods_server_cfg_clerver_encryption_salt_size
         or _irods_server_cfg_clerver_encryption_salt_size | int >= 0'
      - not _irods_server_cfg_home or _irods_server_cfg_home | match('/..*')
      - not _irods_server_cfg_log_level or _irods_server_cfg_log_level | int >= 0
      - 'not _irods_server_cfg_match_hash_policy
         or _irods_server_cfg_match_hash_policy in ["compatible", "strict"]'
      - 'not _irods_server_cfg_ssl_verify_server
         or _irods_server_cfg_ssl_verify_server in ["cert", "hostname", "none"]'
      - 'not _irods_server_cfg_xmsg_port
         or (_irods_server_cfg_xmsg_port | int >= 1
             and _irods_server_cfg_xmsg_port | int <= 65535
             and (not _irods_server_cfg_server_control_plane_port
                  or _irods_server_cfg_xmsg_port != _irods_server_cfg_server_control_plane_port))'
      - 'not _irods_server_cfg_zone_auth_scheme
         or _irods_server_cfg_zone_auth_scheme in ["gsi", "krb", "native", "pam"]'
      - '_irods_server_cfg_zone_port | int >= 1
         and _irods_server_cfg_zone_port | int <= 65535
         and (not _irods_server_cfg_server_control_plane_port
              or _irods_server_cfg_zone_port != _irods_server_cfg_server_control_plane_port)
         and (not  _irods_server_cfg_xmsg_port
              or _irods_server_cfg_zone_port != _irods_server_cfg_xmsg_port)'
#  ignore_errors: true

- name: generate irods environment file
  template:
    src: irods_environment.json.j2
    dest: /var/lib/irods/.irods/irods_environment.json
    owner: "{{ _irods_server_cfg_service_account_name }}"
    group: "{{ _irods_server_cfg_service_group_name }}"
