---
- when: _irods_cfg_icat is mapping
  block:
    - include_tasks: odbc.yml

    - when: _irods_cfg_icat.catalog_database_type == 'postgres'
      include_tasks: pgpass.yml

    - include_tasks: database_config.yml

- import_tasks: host_access_control_config.yml
- import_tasks: hosts_config.yml
- import_tasks: irods_environment.yml
- import_tasks: server_config.yml
- import_tasks: service_account.yml
