---
- when: _irods_cfg_icat is mapping
  import_task: database_config.yml

- import_task: host_access_control_config.yml
- import_task: hosts_config.yml
- import_task: irods_environment.yml
- import_task: server_config.yml
- import_task: service_account.yml
