---
- when: _icat is mapping and _icat.catalog_database_type == 'postgres'
  block:
    - name: validate pgpass config params
      when: _validate | bool
      assert:
        that:
          - _icat.db_port | int >= 1 and _icat.db_port | int <= 65535

    - include_tasks: _cfg_template.yml
      vars:
        _cfg_template_dest_file: var/lib/irods/.pgpass
        _cfg_template_name: pgpass.j2

    - name: assign correct permissions to .pgpass
      file:
        dest: "{{ _root_dir }}/var/lib/irods/.pgpass"
        mode: 'u+r,go='
