---
- when: _irods_cfg_icat is mapping and  _irods_cfg_icat.catalog_database_type == 'postgres'
  block:
    - name: validate pgpass config params
      when: _irods_cfg_validate
      assert:
        that:
          - _irods_cfg_icat.db_port | int >= 1 and _irods_cfg_icat.db_port | int <= 65535

    - include_tasks: _cfg_template.yml
      vars:
        _cfg_template_dest_dir: "{{ _irods_cfg_root_dir }}/var/lib/irods"
        _cfg_template_dest_name: .pgpass
        _cfg_template_name: pgpass.j2

    - name: assign correct permissions to .pgpass
      file:
        dest: "{{ _irods_cfg_root_dir }}/var/lib/irods/.pgpass"
        mode: 'u+r,go='
