---
- name: validate federation
  with_items: "{{ _irods_server_cfg_federation }}"
  assert:
    that:
      - item.icat_host != _irods_server_cfg_icat_host
      - item.zone_name != _irods_server_cfg_zone_name
      - item.negotiation_key | length == 32
  ignore_errors: true

- name: validate other server configuration parameters
  assert:
    that:
      - _irods_server_cfg_default_hash_scheme in ['MD5', 'SHA256']
      - _irods_server_cfg_default_number_of_transfer_threads | int >= 0
      - "not _irods_server_cfg_default_resource_directory
         or _irods_server_cfg_default_resource_directory | match('/.*')"
      - _irods_server_cfg_default_temporary_password_lifetime | int > 0
      - _irods_server_cfg_maximum_number_of_concurrent_rule_engine_server_processes | int >= 1
      - _irods_server_cfg_maximum_size_for_single_buffer | int >= 0
      - '_irods_server_cfg_maximum_temporary_password_lifetime | int
           >= _irods_server_cfg_default_temporary_password_lifetime | int'
      - _irods_server_cfg_match_hash_policy in ['compatible', 'strict']
      - _irods_server_cfg_negotiation_key | length == 32
      - not _irods_server_cfg_pam_no_extend or _irods_server_cfg_pam_no_extend in [true, false]
      - 'not _irods_server_cfg_pam_password_length
         or _irods_server_cfg_pam_password_length | int >= 0'
      - 'not _irods_server_cfg_pam_password_max_time
         or _irods_server_cfg_pam_password_max_time | int > 0'
      - 'not _irods_server_cfg_pam_password_min_time
         or ((_irods_server_cfg_pam_password_min_time | int
                <= _irods_server_cfg_pam_password_max_time | int)
               if _irods_server_cfg_pam_password_max_time else
             (_irods_server_cfg_pam_password_min_time | int > 0))'
      - _irods_server_cfg_server_control_plane_encryption_num_hash_rounds | int >= 0
      - _irods_server_cfg_server_control_plane_key | length == 32
      - '_irods_server_cfg_server_control_plane_port | int >= 1
         and _irods_server_cfg_server_control_plane_port | int <= 65535'
      - _irods_server_cfg_server_control_plane_timeout | int > 0
      - '_irods_server_cfg_server_port_range_end | int >= 1
         and _irods_server_cfg_server_port_range_end | int <= 65535'
      - '_irods_server_cfg_server_port_range_start | int >= 1
         and _irods_server_cfg_server_port_range_start | int
               <= _irods_server_cfg_server_port_range_end | int'
      - '_irods_server_cfg_server_control_plane_port | int
           < _irods_server_cfg_server_port_range_start | int
         or _irods_server_cfg_server_control_plane_port | int
              > _irods_server_cfg_server_port_range_end | int'
      - _irods_server_cfg_transfer_buffer_size_for_parallel_transfer | int > 0
      - _irods_server_cfg_transfer_chunk_size_for_parallel_transfer | int > 0
      - '_irods_server_cfg_xmsg_port | int >= 1
         and _irods_server_cfg_xmsg_port | int <= 65535
         and _irods_server_cfg_xmsg_port != _irods_server_cfg_server_control_plane_port
         and (_irods_server_cfg_xmsg_port | int < _irods_server_cfg_server_port_range_start | int
              or _irods_server_cfg_xmsg_port | int > _irods_server_cfg_server_port_range_end | int)'
      - _irods_server_cfg_zone_auth_scheme in ['gsi', 'krb', 'native', 'pam']
      - not _irods_server_cfg_zone_key | match('.*-.*')
      - '_irods_server_cfg_zone_port | int >= 1
         and _irods_server_cfg_zone_port | int <= 65535
         and _irods_server_cfg_zone_port != _irods_server_cfg_server_control_plane_port
         and (_irods_server_cfg_zone_port | int < _irods_server_cfg_server_port_range_start | int
              or _irods_server_cfg_zone_port | int > _irods_server_cfg_server_port_range_end | int)
         and _irods_server_cfg_zone_port != _irods_server_cfg_xmsg_port'
#  ignore_errors: true

- name: generate server_config.json
  template:
    src: server_config.json.j2
    dest: /etc/irods/server_config.json
    owner: "{{ _irods_server_cfg_service_account_name }}"
    group: "{{ _irods_server_cfg_service_group_name }}"
