---
- name: validate server configuration parameters
  assert:
    that:
      - 'not _irods_server_cfg_default_number_of_transfer_threads
           or _irods_server_cfg_default_number_of_transfer_threads >= 0'
      - 'not _irods_server_cfg_maximum_temporary_password_lifetime
           or ((_irods_server_cfg_maximum_temporary_password_lifetime
                  >= _irods_server_cfg_default_temporary_password_lifetime)
                 if _irods_server_cfg_default_temporary_password_lifetime else
               (_irods_server_cfg_maximum_temporary_password_lifetime > 0))'
      - 'not _irods_server_cfg_default_temporary_password_lifetime
           or _irods_server_cfg_default_temporary_password_lifetime > 0'
      - 'not _irods_server_cfg_maximum_number_of_concurrent_rule_engine_server_processes
           or _irods_server_cfg_maximum_number_of_concurrent_rule_engine_server_processes >= 1'
      - 'not _irods_server_cfg_maximum_size_for_single_buffer
           or _irods_server_cfg_maximum_size_for_single_buffer > 0'
      - 'not _irods_server_cfg_transfer_buffer_size_for_parallel_transfer
           or _irods_server_cfg_transfer_buffer_size_for_parallel_transfer > 0'
      - 'not _irods_server_cfg_transfer_chunk_size_for_parallel_transfer
           or _irods_server_cfg_transfer_chunk_size_for_parallel_transfer > 0'
#  ignore_errors: true

- name: generate server_config.json
  template:
    src: server_config.json.j2
    dest: /etc/irods/server_config.json
    owner: "{{ _irods_server_cfg_service_account_name }}"
    group: "{{ _irods_server_cfg_service_group_name }}"
