---
- name: validate service account vars
  fail:
    msg: not implemented
  failed_when: false

- name: generate service_account.config
  template:
    src: service_account.config.j2
    dest: /etc/irods/service_account.config
    owner: "{{ _irods_server_cfg_service_account_name }}"
    group: "{{ _irods_server_cfg_service_group_name }}"
