---
# These are the config file specific defaults for the server side
# irods_environment.json

_irods_cfg_clerver_default_hash_scheme_default: "{{ _irods_cfg_default_hash_scheme }}"

_irods_cfg_clerver_default_resource_default: "{{
  _irods_cfg_default_resource_name if _irods_cfg_default_resource_name else 'demoResc' }}"

_irods_cfg_clerver_encryption_algorithm_default: "{{
  _irods_cfg_server_control_plane_encryption_algorithm }}"

_irods_cfg_clerver_encryption_key_size_default: 32

_irods_cfg_clerver_encryption_num_hash_rounds_default: "{{
  _irods_cfg_server_control_plane_encryption_num_hash_rounds }}"

_irods_cfg_clerver_encryption_salt_size_default: 8

_irods_cfg_client_server_negotiation_default: request_server_negotiation

_irods_cfg_client_server_policy_default: CS_NEG_DONT_CARE

_irods_cfg_home_default: "{{ '/' ~ _irods_cfg_zone_name ~ '/home/' ~ _irods_cfg_zone_user }}"

_irods_cfg_match_hash_policy_default: compatible
