---
# These are the config file specific defaults for the server side
# irods_environment.json

_client_default_hash_scheme_default: "{{ _default_hash_scheme }}"

_client_default_resource_default: "{{
  _default_resource_name if _default_resource_name else 'demoResc' }}"

_client_encryption_algorithm_default: "{{ _server_control_plane_encryption_algorithm }}"

_client_encryption_key_size_default: 32

_client_encryption_num_hash_rounds_default: "{{ _server_control_plane_encryption_num_hash_rounds }}"

_client_encryption_salt_size_default: 8

_client_server_negotiation_default: request_server_negotiation

_client_server_policy_default: CS_NEG_DONT_CARE

_cwd_default: "{{ _home }}"

_environment_file_default: var/lib/irods/.irods/irods_environment.json

_home_default: "{{ '/' ~ _zone_name ~ '/home/' ~ _zone_user }}"

_match_hash_policy_default: compatible
