---
# These are the config file specific defaults for the server_config.json

_match_hash_policy_default: compatible

_server_control_plane_key_default: TEMPORARY__32byte_ctrl_plane_key

_server_control_plane_port_default: 1248

_zone_auth_scheme_default: native
